modLoader="javafml"

loaderVersion="[39,)"

license="All rights reserved."

[[mods]]

modId="tssdk"
version="${file.jarVersion}"
displayName="Tensei Shitara Slime Datta Ken"
#logoFile="examplemod.png"
credits="Nahli Zayd"

authors="Kazuo, NewMax"

description='''
Welcome! Tensei Shitara Slime Datta Ken Mod.
Support for the mod is only provided in the discord.
You can also share and play with your friends in our dedicated channels !
'''

[[dependencies.tssdk]]

    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tssdk]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
